config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  resource :pages, only: [:index] do
    collection do
      get :default_datepicker
      get :bootstrap_datepicker
      get :tempus_dominus
    end
  end

  resources :products, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index ; end

  def default_datepicker
    @product = Product.new
  end

  def bootstrap_datepicker
    @product = Product.new
  end

  def tempus_dominus
    @product = Product.new
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def create
    @product = Product.new(product_params)
    # binding.pry

    flash[:info] = 'products#create called'
    redirect_to root_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :release_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top justify-content-center">
  <%= link_to 'Date Picker in Rails 6.0', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Datepicker in Rails 6.0</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>

    <% flash.each do |key, value| %>
      <div class="alert alert-info alert-dismissible fade show mb-0">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <div class='text-center'>
          <%= value %>
        </div>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/bootstrap_datepicker.html.erb
<div class='container'>
  <div class='text-center'>
    <h1>Using the gem <code>bootstrap-datepicker-rails</code></h1>
    <p>Implementing datepicker input using <a href='https://github.com/Nerian/bootstrap-datepicker-rails'>bootstrap-datepicker-rails gem</a>.<br /> This is an asset pipeline wrapper for the bootstrap 4 based datepicker - <a href='https://github.com/uxsolutions/bootstrap-datepicker'>https://github.com/uxsolutions/bootstrap-datepicker</a></p>
    <p>
      <%= link_to 'View other examples', root_path, class: 'btn btn-secondary' %>
    </p>
  </div>
</div>

<hr />

<section class='mt-5'>
  <div class='container'>
    <div class='row justify-content-center'>
      <div class='col-md-6 border p-3 rounded'>
        <h4>New Product</h4>
        <hr class='mb-4'/>

        <%= form_with model: @product, local: true do |f| %>

          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :price %>
            <%= f.number_field :price, class: 'form-control' %>
            <small class="form-text text-muted">Price in cents</small>
          </div>

          <div class="form-group">
            <%= f.label :release_date %>
            <%= f.text_field :release_date, class: 'form-control datepicker' %>
            <small class="form-text text-muted">Date when the product will be released.</small>
          </div>

          <%= f.submit class: 'btn btn-primary' %>

        <%- end %>
      </div>
    </div>
  </div>
</section>

app/views/pages/default_datepicker.html.erb
<div class='container'>
  <div class='text-center'>
    <h1>Using the default Rails <code>date_field</code></h1>
    <p>Using the <code>date_field</code> form helper in Rails will render the browser datepicker for <code>&lt;input type='date'&gt;</code>. The view slightly varies across browsers.</p>
    <p>Read about the <a href='https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date'>browser datepicker at MDN</a> docs.</p>
    <p>
      <%= link_to 'View other examples', root_path, class: 'btn btn-secondary' %>
    </p>
  </div>
</div>

<hr />

<section class='mt-5'>
  <div class='container'>
    <div class='row justify-content-center'>
      <div class='col-md-6 border p-3 rounded'>
        <h4>New Product</h4>
        <hr class='mb-4'/>

        <%= form_with model: @product, local: true do |f| %>

          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :price %>
            <%= f.number_field :price, class: 'form-control' %>
            <small class="form-text text-muted">Price in cents</small>
          </div>

          <div class="form-group">
            <%= f.label :release_date %>
            <%= f.date_field :release_date, class: 'form-control' %>
            <small class="form-text text-muted">Date when the product will be released.</small>
          </div>

          <%= f.submit class: 'btn btn-primary' %>

        <%- end %>
      </div>
    </div>
  </div>
</section>

app/views/pages/index.html.erb
<div class='container'>
  <div class='text-center'>
    <h1>3 Ways to Implement Date Picker in Rails 6.0</h1>
    <p>Lets look at 3 ways to implement date picker in Rails 6.0</p>
    <p>For details, read the associated blog post at <a href='https://internetmango.com/blog/implementing-datepicker-in-rails'>Internet Mango Blog</a>.</p>
  </div>
</div>

<hr />

<section class='mt-5'>
  <div class='container'>
    <div class='row'>
      <div class='col-md-4'>
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Default date_field in Rails</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>

            <%= link_to 'View Example', default_datepicker_pages_path, class: 'btn btn-primary' %>
          </div>
        </div>
      </div>

      <div class='col-md-4'>
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Bootstrap Datepicker</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>

            <%= link_to 'View Example', bootstrap_datepicker_pages_path, class: 'btn btn-primary' %>
          </div>
        </div>
      </div>

      <div class='col-md-4'>
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Tempus Dominus Datepicker</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>

            <%= link_to 'View Example', tempus_dominus_pages_path, class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/tempus_dominus.html.erb
<div class='container'>
  <div class='text-center'>
    <h1>Using the gem <code>bs4_datetime_picker</code></h1>
    <p>Implementing datepicker input using <a href='https://github.com/rdavid369/bs4-datetime-picker'>bs4_datetime_picker gem</a>.<br /> This wraps the date time picker js implementation - <a href='https://tempusdominus.github.io/bootstrap-4/'>https://tempusdominus.github.io/bootstrap-4/</a></p>
    <p>
      <%= link_to 'View other examples', root_path, class: 'btn btn-secondary' %>
    </p>
  </div>
</div>

<hr />

<section class='mt-5'>
  <div class='container'>
    <div class='row justify-content-center'>
      <div class='col-md-6 border p-3 rounded'>
        <h4>New Product</h4>
        <hr class='mb-4'/>

        <%= form_with model: @product, local: true do |f| %>

          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :price %>
            <%= f.number_field :price, class: 'form-control' %>
            <small class="form-text text-muted">Price in cents</small>
          </div>

          <div class="form-group">
            <%= f.label :release_date %>
            <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
              <%= f.text_field :release_date, class: 'form-control datetimepicker-input', 'data-target': "#datetimepicker1" %>
              <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                <div class="input-group-text"><i class='fa fa-calendar'></i></div>
              </div>
            </div>
            <small class="form-text text-muted">Date when the product will be released.</small>
          </div>

          <%= f.submit class: 'btn btn-primary' %>

        <%- end %>
      </div>
    </div>
  </div>
</section>